stratis-storage/libblkid-rs

.github/workflows/main.yml, Makefile, src/dev.rs, src/probe.rs
=> Add Github Actions

.github/workflows/main.yml
Related: stratis-storage/project#240
=> github actions: update lowest supported Rust to 1.47

.github/workflows/main.yml
Related: stratis-storage/project#266
=> Increase recommended development version to 1.50.0

.github/workflows/main.yml, Makefile, src/encode.rs
Related: stratis-storage/project#276
=> Update Rust lints for 1.51

.github/workflows/main.yml, Makefile
Supersedes: #20 
Related stratis-storage/project#307
=> Makefile: Add check-fedora-versions-sys target

.github/workflows/main.yml, .github/workflows/nightly.yml
Related: stratis-storage/project#315
=> Increase recommended development version to 1.53.0

.github/workflows/main.yml, Cargo.toml, Makefile, libblkid-rs-sys/Cargo.toml
Related  https://github.com/stratis-storage/project/issues/285
=> Verify dependency bounds and bump required versions

.github/workflows/cargo.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
Related: stratis-storage/project#337
Related: stratis-storage/project#321
=> github actions: update recommended Rust to 1.54

.github/workflows/weekly.yml
Related: stratis-storage/ci#219
=> github actions: Annotate development environments

src/encode.rs
Closes #51 
The link for the koji build with this change applied is here: https://koji.fedoraproject.org/koji/taskinfo?taskID=78322135
=> Fix casting bug

.github/workflows/dummy.yml, .github/workflows/main.yml
=> Tidy up CI

Cargo.toml, libblkid-rs-sys/Cargo.toml
Related: stratis-storage/project#413
=> Add cargo categories

Cargo.toml, Makefile, libblkid-rs-sys/Cargo.toml, libblkid-rs-sys/src/lib.rs
Related https://github.com/stratis-storage/project/issues/351
=> Run clippy on -sys library as well

src/cache.rs, src/dev.rs, src/lib.rs
Related to stratis-storage/stratisd#2949
=> Add blkid_verify

.github/workflows/cargo.yml, .github/workflows/nightly.yml, Makefile
Related https://github.com/stratis-storage/project/issues/377
=> Increase lower release to f35 for check-fedora-versions

Cargo.toml
Related https://github.com/stratis-storage/project/issues/491
=> Update low reqs

.github/workflows/cargo.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
Related: stratis-storage/project#500
=> github actions: update recommended Rust to 1.63

Cargo.toml, Makefile, libblkid-rs-sys/Cargo.toml, src/probe.rs
Related https://github.com/stratis-storage/project/issues/335
=> Update to edition 2021

libblkid-rs-sys/Cargo.toml
Related https://github.com/stratis-storage/project/issues/507
=> libblkid-rs-sys v0.1.4

.github/workflows/cargo.yml, .github/workflows/dummy.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
Related https://github.com/stratis-storage/project/issues/525
=> Update ubuntu image to 20.04

src/probe.rs
Related: https://github.com/stratis-storage/project/issues/545
=> BlkidProbe: fix bool_to_int_with_if clippy error

.github/workflows/cargo.yml, .github/workflows/nightly.yml
Related: stratis-storage/project#501
=> Update Fedora releases for version compare CI

libblkid-rs-sys/Cargo.toml
Related: stratis-storage/project#551
=> Set bindgen dependency to 0.63.0

CHANGES.txt, Cargo.toml
Related https://github.com/stratis-storage/project/issues/567
=> libblkid-rs v0.3.0

examples/is_owned.rs, src/err.rs
Related: stratis-storage/project#572
=> Resolve clippy 1.67 errors

libblkid-rs-sys/Cargo.toml
=> libblkid-rs-sys v0.1.5

.github/workflows/cargo.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
Related: stratis-storage/project#619
=> github actions: update recommended Rust to 1.70.0

.github/workflows/cargo.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
Related: stratis-storage/project#655
=> github actions: update recommended Rust to 1.72.0

.githooks/pre-commit, .github/workflows/main.yml, Makefile, src/cache.rs, src/partition.rs, src/probe.rs, src/utils.rs
Related: stratis-storage/project#663
=> Add typos target to Makefile

libblkid-rs-sys/Cargo.toml
Related: stratis-storage/project#662
=> Set bindgen dependency to 0.68.1

Cargo.toml, libblkid-rs-sys/Cargo.toml
Related https://github.com/stratis-storage/project/issues/665
=> libblkid-rs-sys v0.2.0

.github/workflows/cargo.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
Related: stratis-storage/project#687
=> github actions: update recommended Rust to 1.76.0

CHANGES.txt, Cargo.toml
Related https://github.com/stratis-storage/project/issues/699
=> libblkid-rs v0.3.2

.github/workflows/cargo.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
Related: stratis-storage/project#703
=> github actions: update recommended Rust to 1.78.0

libblkid-rs-sys/Cargo.toml
Related: stratis-storage/project#716
=> Change deprecated default_features to default-features

Cargo.toml, Makefile, libblkid-rs-sys/Cargo.toml
Related https://github.com/stratis-storage/project/issues/721
=> Use Cargo.toml to specify lint policy

.github/workflows/cargo.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
Related: stratis-storage/project#723
=> github actions: update recommended Rust to 1.80.1

Makefile
Related https://github.com/stratis-storage/project/issues/451
=> Add PROFILE_FLAGS to profileable targets

.github/workflows/nightly.yml
Related https://github.com/stratis-storage/project/issues/731
=> Run semantic version checks nightly

.github/workflows/cargo.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
Related: stratis-storage/project#747
=> github actions: update recommended Rust to 1.84.0

.github/workflows/cargo.yml, .github/workflows/dummy.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
Related https://github.com/stratis-storage/project/issues/752
=> Use Ubuntu 22.04 image

CHANGES.txt, Cargo.toml
Related https://github.com/stratis-storage/project/issues/748
=> libblkid-rs v0.4.0

.github/workflows/nightly.yml, Makefile
Related https://github.com/stratis-storage/project/issues/778
=> Remove PATH and install management for audit task

.github/workflows/cargo.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
Related https://github.com/stratis-storage/project/issues/795
=> github actions: Update recommended Rust to 1.89.0
